var searchData=
[
  ['a_202d_20mesh_20from_20gmsh_0',['MSH-1: Create a 2D mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'']]],
  ['a_203d_20mesh_20from_20gmsh_1',['MSH-2: Create a 3D mesh from Gmsh',['../basic_tutorials_mesh_generation_3d.html',1,'']]],
  ['a_20good_20citizen_2',['Being a good citizen',['../being_a_good_citizen.html',1,'']]],
  ['a_20new_20module_20and_20program_3',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['a_20nonlinear_20poisson_20equation_4',['COR-5: A nonlinear Poisson equation',['../poisson_tut4.html',1,'tutorials']]],
  ['a_20program_5',['How to compile a program',['../how_to_compile_program.html',1,'']]],
  ['a_20tutorial_20from_20core_6',['How to Copy a Tutorial from Core',['../md_users__modules_2_how_to_copy_tutorial.html',1,'']]],
  ['about_7',['About',['../about_us.html',1,'']]],
  ['acoustics_8',['acoustics',['../md_tutorials_2clx-0_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics'],['../md_tutorials_2mix-1_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics'],['../md_tutorials_2vec-2_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics']]],
  ['adaptivity_9',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['add_20a_20new_20module_20and_20program_10',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['adolc_5fplasticity_11',['adolc_plasticity',['../md_users__modules_2adolc-plasticity_2adolc__plasticity.html',1,'']]],
  ['adv_200_3a_20plastic_20problem_12',['ADV-0: Plastic problem',['../tutorial_plastic_problem.html',1,'']]],
  ['adv_201_3a_20contact_20problem_13',['ADV-1: Contact problem',['../tutorial_contact_problem.html',1,'']]],
  ['adv_202_3a_20thermo_20elastic_20example_14',['ADV-2: Thermo-elastic example',['../tutorial_thermo_elastic.html',1,'']]],
  ['adv_203_3a_20dg_20upwind_20for_20advection_20problem_20or_20level_20set_15',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['adv_205_3a_20seepage_20in_20elsatic_20body_20example_16',['ADV-5: Seepage in elsatic body example',['../tutorial_seepage.html',1,'']]],
  ['advanced_17',['Installation with Spack (Advanced)',['../install_spack.html',1,'installation']]],
  ['advanced_18',['Installation with Docker - advanced',['../install_docker_advanced.html',1,'']]],
  ['advection_20problem_20or_20level_20set_19',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['an_20environmental_20change_20',['an Environmental Change',['../gel_layered.html',1,'Layered Gel Problem (Response to an Environmental Change)'],['../gel_cell.html',1,'Wood Cell (Response to an Environmental Change)']]],
  ['an_20environmental_20change_21',['Gel Model Sorption (response to an environmental change)',['../gel_sorption.html',1,'runningprograms']]],
  ['an_20external_20pr_22',['How to: Squashing for an external PR',['../_squash_f_a_q.html',1,'']]],
  ['and_20dm_20sub_20problem_23',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['and_20industry_24',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['and_20integration_20on_20skeleton_20h_20adaptivity_25',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['and_20login_26',['Password and login',['../md__2_users_2likask_2mofem__install_2mofem-cephas_2jupyter_2templates_2login__notes.html',1,'']]],
  ['and_20navier_20stokes_27',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['and_20program_28',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['and_20sustainable_20code_20development_29',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['applications_20of_20mofem_20in_20research_20and_20industry_30',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['approximation_31',['FUN-2: Hierarchical approximation',['../hierarchical_approximation_1.html',1,'']]],
  ['approximaton_32',['SCL-0: Least square approximaton',['../basic_tutorials_least_square_approximation.html',1,'']]],
  ['architecture_33',['MoFEM Architecture',['../general_data_structure.html',1,'']]],
  ['asked_20questions_34',['Frequently Asked Questions',['../faqs.html',1,'']]],
  ['authors_35',['MoFEM Authors',['../authors.html',1,'']]],
  ['automatic_20differentiation_20for_20plasticity_36',['VEC-7: Automatic Differentiation for Plasticity',['../tutorial_adolc_plasticity.html',1,'']]],
  ['autumn_20school_202023_3a_20mixed_20finite_20element_20formulations_20in_20solid_20mechanics_37',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]]
];
