var searchData=
[
  ['page_0',['Landing page',['../index.html',1,'']]],
  ['paper_1',['paper',['../md__2_users_2likask_2mofem__install_2mofem-cephas_2joss_2paper.html',1,'']]],
  ['partition_2',['partition',['../md_tutorials_2scl-2_2_r_e_a_d_m_e.html',1,'Mesh partition'],['../md_tutorials_2scl-3_2_r_e_a_d_m_e.html',1,'Mesh partition']]],
  ['password_20and_20login_3',['Password and login',['../md__2_users_2likask_2mofem__install_2mofem-cephas_2jupyter_2templates_2login__notes.html',1,'']]],
  ['periodic_20boundary_20conditions_20with_20nitsche_20s_20method_4',['Periodic boundary conditions with Nitsche&apos;s method',['../nitsche_periodic.html',1,'runningprograms']]],
  ['phase_20field_20model_20and_20navier_20stokes_5',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['phase_20solving_20transport_20of_20intensity_20equation_6',['MIX-1: Retrive phase solving transport-of-intensity equation.',['../tutorial_phase.html',1,'']]],
  ['photon_20diffusion_7',['Photon diffusion',['../md_tutorials_2scl-10_2_r_e_a_d_m_e.html',1,'Photon diffusion'],['../tutorials_photon_diffusion.html',1,'SCL-10: Photon diffusion']]],
  ['plastic_20problem_8',['ADV-0: Plastic problem',['../tutorial_plastic_problem.html',1,'']]],
  ['plasticity_9',['Plasticity',['../jup_plasticity.html',1,'Plasticity'],['../tutorial_adolc_plasticity.html',1,'VEC-7: Automatic Differentiation for Plasticity']]],
  ['plasticity_20module_10',['Eshelbian plasticity module',['../um_eshelbian_plasticity_readme.html',1,'']]],
  ['plasticity_20user_20example_11',['Plasticity (User example)',['../small_strain_plasticity_plate_with_hole.html',1,'runningprograms']]],
  ['plate_12',['VEC-6: Discontinuous Galerkin for Kirchoff-Love Plate',['../tutorial_plate.html',1,'']]],
  ['plate_13',['Elastoplastic plate',['../jup_tutorial_plastic_problem.html',1,'running_code']]],
  ['plate_20with_20hole_14',['Plate with hole',['../jup_plate_with_hole.html',1,'jup_tutorial_plastic_problem']]],
  ['pluto_15',['pluto',['../md_tutorials_2scl-8_2pluto.html',1,'']]],
  ['poisson_20equation_16',['Poisson equation',['../poisson_tut1.html',1,'COR-2: Solving the Poisson equation'],['../poisson_tut2.html',1,'COR-3: Implementing operators for the Poisson equation'],['../poisson_tut4.html',1,'COR-5: A nonlinear Poisson equation'],['../tut_mix_poisson.html',1,'MIX-0: Mixed formulation of Poisson equation']]],
  ['poisson_20problem_17',['SCL-11: Discontinuous Galerkin for Poisson problem',['../tutorial_dg_poisson.html',1,'']]],
  ['poisson_20s_20equation_18',['SCL-4: Nonlinear Poisson&apos;s equation',['../basic_tutorials_poisson_nonlinear.html',1,'']]],
  ['poisson_20s_20equation_20homogeneous_20bc_19',['SCL-1: Poisson&apos;s equation (homogeneous BC)',['../basic_tutorials_poisson_homogeneous.html',1,'']]],
  ['poisson_20s_20equation_20lagrange_20multiplier_20',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]],
  ['poisson_20s_20equation_20non_20homogeneous_20bc_21',['SCL-2: Poisson&apos;s equation (non-homogeneous BC)',['../basic_tutorials_poisson_nonhomogeneous.html',1,'']]],
  ['pr_22',['How to: Squashing for an external PR',['../_squash_f_a_q.html',1,'']]],
  ['practice_23',['Coding practice',['../coding_practice.html',1,'']]],
  ['problem_24',['problem',['../tutorial_plastic_problem.html',1,'ADV-0: Plastic problem'],['../tutorial_contact_problem.html',1,'ADV-1: Contact problem'],['../tutorial_hemholtz_problem.html',1,'CLX-0: Helmholtz problem'],['../poisson_tut3.html',1,'COR-4: Using fieldsplit solver and DM sub problem.'],['../md_tutorials_2vec-1_2_r_e_a_d_m_e.html',1,'Readme for eiegn problem'],['../md_tutorials_2vec-1_2eigen__elastic.html',1,'Running problem'],['../tutorial_dg_poisson.html',1,'SCL-11: Discontinuous Galerkin for Poisson problem']]],
  ['problem_20or_20level_20set_25',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['problem_20response_20to_20an_20environmental_20change_26',['Layered Gel Problem (Response to an Environmental Change)',['../gel_layered.html',1,'runningprograms']]],
  ['program_27',['program',['../how_to_add_new_module_and_program.html',1,'How to add a new module and program'],['../how_to_compile_program.html',1,'How to compile a program']]],
  ['programs_28',['Programs',['../runningprograms.html',1,'']]],
  ['propagation_20tests_20edf_20tests_29',['Benchmarks crack propagation tests (EDF Tests)',['../benchmarks_edf_tets.html',1,'mod_gallery']]],
  ['publications_20featuring_20results_20obtained_20using_20mofem_30',['Selected publications featuring results obtained using MoFEM',['../publications.html',1,'']]]
];
