var searchData=
[
  ['macos_0',['Installation on macOS',['../install_macosx.html',1,'']]],
  ['magnetostatics_1',['MAX-0: Magnetostatics',['../tutorial_magnetostatic.html',1,'']]],
  ['make_20notebook_20tt_2',['Command: &lt;tt&gt;make notebook&lt;/tt&gt;',['../md_tutorials_2README.html',1,'']]],
  ['make_20notebook_5fscl_208_3',['Command: make notebook_scl-8',['../md_tutorials_2scl-8_2README.html',1,'']]],
  ['many_20flavours_20design_20and_20sustainable_20code_20development_4',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['max_200_3a_20magnetostatics_5',['MAX-0: Magnetostatics',['../tutorial_magnetostatic.html',1,'']]],
  ['max_201_3a_20lorenz_20force_6',['MAX-1: Lorenz force',['../tutorial_lorenz_force.html',1,'']]],
  ['mechanics_7',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['med_20file_20exported_20from_20gmsh_20geo_20file_8',['med file exported from gmsh geo file',['../md_tutorials_2msh-2_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-1_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['mesh_9',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['mesh_20from_20gmsh_10',['mesh from gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'MSH-1: Create a 2D mesh from Gmsh'],['../basic_tutorials_mesh_generation_3d.html',1,'MSH-2: Create a 3D mesh from Gmsh']]],
  ['mesh_20partition_11',['mesh partition',['../md_tutorials_2scl-3_2README.html',1,'Mesh partition'],['../md_tutorials_2scl-2_2README.html',1,'Mesh partition']]],
  ['method_12',['SCL-9: Heat method',['../tutorial_heat_method.html',1,'']]],
  ['minimal_20surface_20equation_13',['SCL-5: Minimal surface equation',['../basic_tutorials_minimal_surface_equation.html',1,'']]],
  ['mix_200_3a_20mixed_20formulation_20of_20poisson_20equation_14',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['mix_201_3a_20retrive_20phase_20solving_20transport_20of_20intensity_20equation_15',['MIX-1: Retrive phase solving transport-of-intensity equation.',['../tutorial_phase.html',1,'']]],
  ['mix_202_3a_20mixed_20formulation_20for_20incompressible_20elasticity_16',['MIX-2: Mixed  formulation for incompressible elasticity',['../incompressible_elasticity.html',1,'']]],
  ['mix_20formulation_20unsaturated_20flow_17',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['mixed_20finite_20element_20formulations_20in_20solid_20mechanics_18',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['mixed_20formulation_20and_20integration_20on_20skeleton_20h_20adaptivity_19',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['mixed_20formulation_20for_20incompressible_20elasticity_20',['mixed formulation for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['mixed_20formulation_20of_20nonlinear_20elasticity_21',['COR-11: Mixed formulation of nonlinear elasticity',['../tutorial_ep.html',1,'tutorials']]],
  ['mixed_20formulation_20of_20poisson_20equation_22',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['model_20and_20navier_20stokes_23',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['module_24',['Eshelbian plasticity module',['../um_eshelbian_plasticity_readme.html',1,'']]],
  ['module_20and_20program_25',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['modules_26',['Users modules',['../mod_gallery.html',1,'']]],
  ['mofem_27',['mofem',['../contributing_to_mofem.html',1,'Contributing to MoFEM'],['../publications.html',1,'Selected publications featuring results obtained using MoFEM']]],
  ['mofem_20architecture_28',['MoFEM Architecture',['../general_data_structure.html',1,'']]],
  ['mofem_20authors_29',['MoFEM Authors',['../authors.html',1,'']]],
  ['mofem_20cephas_20strong_30',['&lt;strong&gt;MoFEM (Cephas)&lt;/strong&gt;',['../md__2home_2lk58p_2mofem__install_2vanilla__dev__release_2mofem-cephas_2README.html',1,'']]],
  ['mofem_20in_20research_20and_20industry_31',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['mofem_20interfaces_32',['MoFEM Interfaces',['../lessons_introduction.html',1,'']]],
  ['mofem_20ukacm_202021_20school_3a_20weak_20form_20in_20many_20flavours_20design_20and_20sustainable_20code_20development_33',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['mofem_20ukacm_20autumn_20school_202023_3a_20mixed_20finite_20element_20formulations_20in_20solid_20mechanics_34',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['mofem_20v0_2013_200_35',['MoFEM v0.13.0',['../md_CHANGELOG.html',1,'']]],
  ['msh_201_3a_20create_20a_202d_20mesh_20from_20gmsh_36',['MSH-1: Create a 2D mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'']]],
  ['msh_202_3a_20create_20a_203d_20mesh_20from_20gmsh_37',['MSH-2: Create a 3D mesh from Gmsh',['../basic_tutorials_mesh_generation_3d.html',1,'']]],
  ['multiplier_38',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]]
];
