var searchData=
[
  ['cephas_20strong_0',['&lt;strong&gt;MoFEM (Cephas)&lt;/strong&gt;',['../md__2home_2lk58p_2mofem__install_2vanilla__dev__release_2mofem-cephas_2README.html',1,'']]],
  ['check_20before_20run_1',['Check before run',['../md_tutorials_2max-0_2README.html',1,'']]],
  ['citizen_2',['Being a good citizen',['../being_a_good_citizen.html',1,'']]],
  ['clx_200_3a_20helmholtz_20problem_3',['CLX-0: Helmholtz problem',['../tutorial_hemholtz_problem.html',1,'']]],
  ['code_4',['code',['../md_tutorials_2adv-2_2README.html',1,'Running code'],['../md_tutorials_2adv-4_2README.html',1,'Running code'],['../md_tutorials_2adv-5_2README.html',1,'Running code'],['../running_code.html',1,'Running code']]],
  ['code_20development_5',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['coding_20practice_6',['Coding practice',['../coding_practice.html',1,'']]],
  ['command_3a_20make_20notebook_5fscl_208_7',['Command: make notebook_scl-8',['../md_tutorials_2scl-8_2README.html',1,'']]],
  ['command_3a_20tt_20make_20notebook_20tt_8',['Command: &lt;tt&gt;make notebook&lt;/tt&gt;',['../md_tutorials_2README.html',1,'']]],
  ['compile_20a_20program_9',['How to compile a program',['../how_to_compile_program.html',1,'']]],
  ['conditions_10',['SCL-8: Radiation boundary conditions',['../jup_radiation_pluto.html',1,'running_code']]],
  ['contact_20problem_11',['ADV-1: Contact problem',['../tutorial_contact_problem.html',1,'']]],
  ['contributing_20to_20mofem_12',['Contributing to MoFEM',['../contributing_to_mofem.html',1,'']]],
  ['cor_200_3a_20mixed_20formulation_20and_20integration_20on_20skeleton_20h_20adaptivity_13',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['cor_2010_3a_20navier_20stokes_20equation_14',['COR-10: Navier-Stokes equation',['../tutorial_navier_stokes.html',1,'tutorials']]],
  ['cor_2011_3a_20mixed_20formulation_20of_20nonlinear_20elasticity_15',['COR-11: Mixed formulation of nonlinear elasticity',['../tutorial_ep.html',1,'tutorials']]],
  ['cor_201_3a_20time_20dependent_20nonlinear_20mix_20formulation_20unsaturated_20flow_16',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['cor_202_3a_20solving_20the_20poisson_20equation_17',['COR-2: Solving the Poisson equation',['../poisson_tut1.html',1,'tutorials']]],
  ['cor_203_3a_20implementing_20operators_20for_20the_20poisson_20equation_18',['COR-3: Implementing operators for the Poisson equation',['../poisson_tut2.html',1,'tutorials']]],
  ['cor_204_3a_20using_20fieldsplit_20solver_20and_20dm_20sub_20problem_19',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['cor_205_3a_20a_20nonlinear_20poisson_20equation_20',['COR-5: A nonlinear Poisson equation',['../poisson_tut4.html',1,'tutorials']]],
  ['cor_206_3a_20solid_20elasticity_21',['COR-6: Solid elasticity',['../simple_elasticity_1.html',1,'tutorials']]],
  ['cor_207_3a_20mixed_20formulation_20for_20incompressible_20elasticity_22',['COR-7: Mixed formulation for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'tutorials']]],
  ['cor_208_3a_20implementation_20of_20spring_20element_23',['COR-8: Implementation of spring element',['../spring_element.html',1,'tutorials']]],
  ['cor_209_3a_20reaction_20diffusion_20equation_24',['COR-9: Reaction-diffusion equation',['../reaction_diffusion_imp.html',1,'tutorials']]],
  ['create_20a_202d_20mesh_20from_20gmsh_25',['MSH-1: Create a 2D mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'']]],
  ['create_20a_203d_20mesh_20from_20gmsh_26',['MSH-2: Create a 3D mesh from Gmsh',['../basic_tutorials_mesh_generation_3d.html',1,'']]],
  ['create_20h5m_20file_20from_20med_20file_20exported_20from_20gmsh_20geo_20file_27',['create h5m file from med file exported from gmsh geo file',['../md_tutorials_2msh-1_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]]
];
