var searchData=
[
  ['s_20equation_0',['SCL-4: Nonlinear Poisson&apos;s equation',['../basic_tutorials_poisson_nonlinear.html',1,'']]],
  ['s_20equation_20homogeneous_20bc_1',['SCL-1: Poisson&apos;s equation (homogeneous BC)',['../basic_tutorials_poisson_homogeneous.html',1,'']]],
  ['s_20equation_20lagrange_20multiplier_2',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]],
  ['s_20equation_20non_20homogeneous_20bc_3',['SCL-2: Poisson&apos;s equation (non-homogeneous BC)',['../basic_tutorials_poisson_nonhomogeneous.html',1,'']]],
  ['school_202023_3a_20mixed_20finite_20element_20formulations_20in_20solid_20mechanics_4',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['school_3a_20weak_20form_20in_20many_20flavours_20design_20and_20sustainable_20code_20development_5',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['scl_200_3a_20least_20square_20approximaton_6',['SCL-0: Least square approximaton',['../basic_tutorials_least_square_approximation.html',1,'']]],
  ['scl_2010_3a_20photon_20diffusion_7',['SCL-10: Photon diffusion',['../tutorials_photon_diffusion.html',1,'']]],
  ['scl_2011_3a_20discontinuous_20galerkin_20for_20poisson_20problem_8',['SCL-11: Discontinuous Galerkin for Poisson problem',['../tutorial_dg_poisson.html',1,'']]],
  ['scl_201_3a_20poisson_20s_20equation_20homogeneous_20bc_9',['SCL-1: Poisson&apos;s equation (homogeneous BC)',['../basic_tutorials_poisson_homogeneous.html',1,'']]],
  ['scl_202_3a_20poisson_20s_20equation_20non_20homogeneous_20bc_10',['SCL-2: Poisson&apos;s equation (non-homogeneous BC)',['../basic_tutorials_poisson_nonhomogeneous.html',1,'']]],
  ['scl_203_3a_20poisson_20s_20equation_20lagrange_20multiplier_11',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]],
  ['scl_204_3a_20nonlinear_20poisson_20s_20equation_12',['SCL-4: Nonlinear Poisson&apos;s equation',['../basic_tutorials_poisson_nonlinear.html',1,'']]],
  ['scl_205_3a_20minimal_20surface_20equation_13',['SCL-5: Minimal surface equation',['../basic_tutorials_minimal_surface_equation.html',1,'']]],
  ['scl_206_3a_20heat_20equation_14',['SCL-6: Heat equation',['../basic_tutorials_heat_equation.html',1,'']]],
  ['scl_207_3a_20wave_20equation_15',['SCL-7: Wave equation',['../basic_tutorials_wave_equation.html',1,'']]],
  ['scl_208_3a_20radiation_20boundary_20conditions_16',['SCL-8: Radiation boundary conditions',['../jup_radiation_pluto.html',1,'running_code']]],
  ['scl_209_3a_20heat_20method_17',['SCL-9: Heat method',['../tutorial_heat_method.html',1,'']]],
  ['scripts_18',['Installation with Spack (Scripts)',['../installation.html',1,'']]],
  ['search_19',['Search',['../google_search.html',1,'']]],
  ['seepage_20in_20elsatic_20body_20example_20',['ADV-5: Seepage in elsatic body example',['../tutorial_seepage.html',1,'']]],
  ['selected_20publications_20featuring_20results_20obtained_20using_20mofem_21',['Selected publications featuring results obtained using MoFEM',['../publications.html',1,'']]],
  ['set_22',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['shallow_20wave_20equation_20on_20sphere_23',['VEC-4: Shallow wave equation on sphere',['../shallow_wave_doc.html',1,'']]],
  ['skeleton_20h_20adaptivity_24',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['solid_20elasticity_25',['COR-6: Solid elasticity',['../simple_elasticity_1.html',1,'tutorials']]],
  ['solid_20mechanics_26',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['solver_20and_20dm_20sub_20problem_27',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['solving_20the_20poisson_20equation_28',['COR-2: Solving the Poisson equation',['../poisson_tut1.html',1,'tutorials']]],
  ['solving_20transport_20of_20intensity_20equation_29',['MIX-1: Retrive phase solving transport-of-intensity equation.',['../tutorial_phase.html',1,'']]],
  ['spack_20advanced_30',['Installation with Spack (Advanced)',['../install_spack.html',1,'installation']]],
  ['spack_20scripts_31',['Installation with Spack (Scripts)',['../installation.html',1,'']]],
  ['sphere_32',['VEC-4: Shallow wave equation on sphere',['../shallow_wave_doc.html',1,'']]],
  ['spring_20element_33',['COR-8: Implementation of spring element',['../spring_element.html',1,'tutorials']]],
  ['square_20approximaton_34',['SCL-0: Least square approximaton',['../basic_tutorials_least_square_approximation.html',1,'']]],
  ['squashing_20for_20an_20external_20pr_35',['How to: Squashing for an external PR',['../SquashFAQ.html',1,'']]],
  ['stokes_36',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['stokes_20equation_37',['COR-10: Navier-Stokes equation',['../tutorial_navier_stokes.html',1,'tutorials']]],
  ['strong_20mofem_20cephas_20strong_38',['&lt;strong&gt;MoFEM (Cephas)&lt;/strong&gt;',['../md__2home_2lk58p_2mofem__install_2vanilla__dev__release_2mofem-cephas_2README.html',1,'']]],
  ['sub_20problem_39',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['surface_20equation_40',['SCL-5: Minimal surface equation',['../basic_tutorials_minimal_surface_equation.html',1,'']]],
  ['sustainable_20code_20development_41',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]]
];
