var searchData=
[
  ['features_0',['Features',['../motivation.html',1,'']]],
  ['featuring_20results_20obtained_20using_20mofem_1',['Selected publications featuring results obtained using MoFEM',['../publications.html',1,'']]],
  ['field_20model_20and_20navier_20stokes_2',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['fieldsplit_20solver_20and_20dm_20sub_20problem_3',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['file_20from_20med_20file_20exported_20from_20gmsh_20geo_20file_4',['file from med file exported from gmsh geo file',['../md_tutorials_2msh-2_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-1_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['film_20spanned_20on_20wire_5',['Soap film spanned on wire',['../sope_film.html',1,'tutorials']]],
  ['finite_20element_20formulations_20in_20solid_20mechanics_6',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['finite_20element_20mesh_7',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['flavours_20design_20and_20sustainable_20code_20development_8',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['flow_9',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['for_20advection_20problem_20or_20level_20set_10',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['for_20an_20external_20pr_11',['How to: Squashing for an external PR',['../SquashFAQ.html',1,'']]],
  ['for_20bug_20reporting_12',['Guidelines for bug reporting',['../guidelines_bug_reporting.html',1,'']]],
  ['for_20eiegn_20problem_13',['Readme for eiegn problem',['../md_tutorials_2vec-1_2README.html',1,'']]],
  ['for_20incompressible_20elasticity_14',['for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['for_20kirchoff_20love_20plate_15',['VEC-6: Discontinuous Galerkin for Kirchoff-Love Plate',['../tutorial_plate.html',1,'']]],
  ['for_20linear_20acoustics_16',['for linear acoustics',['../md_tutorials_2clx-0_2README.html',1,'Readme for linear acoustics'],['../md_tutorials_2vec-2_2README.html',1,'Readme for linear acoustics'],['../md_tutorials_2mix-1_2README.html',1,'Readme for linear acoustics']]],
  ['for_20linear_20elasticity_17',['Readme for linear elasticity',['../md_tutorials_2vec-0_2README.html',1,'']]],
  ['for_20poisson_20problem_18',['SCL-11: Discontinuous Galerkin for Poisson problem',['../tutorial_dg_poisson.html',1,'']]],
  ['for_20the_20poisson_20equation_19',['COR-3: Implementing operators for the Poisson equation',['../poisson_tut2.html',1,'tutorials']]],
  ['force_20',['MAX-1: Lorenz force',['../tutorial_lorenz_force.html',1,'']]],
  ['fork_21',['Tuning fork',['../jup_tutorial_eigen_elastic.html',1,'running_code']]],
  ['form_20in_20many_20flavours_20design_20and_20sustainable_20code_20development_22',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['formulation_20and_20integration_20on_20skeleton_20h_20adaptivity_23',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['formulation_20for_20incompressible_20elasticity_24',['formulation for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['formulation_20of_20nonlinear_20elasticity_25',['COR-11: Mixed formulation of nonlinear elasticity',['../tutorial_ep.html',1,'tutorials']]],
  ['formulation_20of_20poisson_20equation_26',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['formulation_20unsaturated_20flow_27',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['formulations_20in_20solid_20mechanics_28',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['frequently_20asked_20questions_29',['Frequently Asked Questions',['../faqs.html',1,'']]],
  ['from_20ct_20scans_30',['Density mapping from CT scans',['../density_map_example.html',1,'runningprograms']]],
  ['from_20gmsh_31',['from gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'MSH-1: Create a 2D mesh from Gmsh'],['../basic_tutorials_mesh_generation_3d.html',1,'MSH-2: Create a 3D mesh from Gmsh']]],
  ['from_20med_20file_20exported_20from_20gmsh_20geo_20file_32',['from med file exported from gmsh geo file',['../md_tutorials_2msh-2_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-1_2README.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['ftensor_20library_33',['FTensor library',['../group__ftensor.html',1,'']]],
  ['fun_200_3a_20hello_20world_34',['FUN-0: Hello world',['../hello_world_tut1.html',1,'']]],
  ['fun_201_3a_20integration_20on_20finite_20element_20mesh_35',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['fun_202_3a_20hierarchical_20approximation_36',['FUN-2: Hierarchical approximation',['../hierarchical_approximation_1.html',1,'']]],
  ['functions_37',['Genarting base functions',['../md_tutorials_2fun-2_2README.html',1,'']]]
];
