var searchData=
[
  ['macos_0',['Installation on macOS',['../install_macosx.html',1,'']]],
  ['magnetostatics_1',['MAX-0: Magnetostatics',['../tutorial_magnetostatic.html',1,'']]],
  ['make_20notebook_20tt_2',['Command: &lt;tt&gt;make notebook&lt;/tt&gt;',['../md_tutorials_2_r_e_a_d_m_e.html',1,'']]],
  ['make_20notebook_5fscl_208_3',['Command: make notebook_scl-8',['../md_tutorials_2scl-8_2_r_e_a_d_m_e.html',1,'']]],
  ['many_20flavours_20design_20and_20sustainable_20code_20development_4',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['mapping_20from_20ct_20scans_5',['Density mapping from CT scans',['../density_map_example.html',1,'runningprograms']]],
  ['max_200_3a_20magnetostatics_6',['MAX-0: Magnetostatics',['../tutorial_magnetostatic.html',1,'']]],
  ['max_201_3a_20lorenz_20force_7',['MAX-1: Lorenz force',['../tutorial_lorenz_force.html',1,'']]],
  ['mechanics_8',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['mechanics_20module_9',['Fracture mechanics module',['../um_fracture_module_readme.html',1,'mod_gallery']]],
  ['mechanics_20usage_20examples_10',['Fracture Mechanics (Usage Examples)',['../frac_mech_simple_examples.html',1,'running_code']]],
  ['med_20file_20exported_20from_20gmsh_20geo_20file_11',['med file exported from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['mesh_12',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['mesh_20from_20gmsh_13',['mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'MSH-1: Create a 2D mesh from Gmsh'],['../basic_tutorials_mesh_generation_3d.html',1,'MSH-2: Create a 3D mesh from Gmsh']]],
  ['mesh_20partition_14',['Mesh partition',['../md_tutorials_2scl-2_2_r_e_a_d_m_e.html',1,'Mesh partition'],['../md_tutorials_2scl-3_2_r_e_a_d_m_e.html',1,'Mesh partition']]],
  ['method_15',['method',['../nitsche_periodic.html',1,'Periodic boundary conditions with Nitsche&apos;s method'],['../tutorial_heat_method.html',1,'SCL-9: Heat method']]],
  ['minimal_20surface_20equation_16',['SCL-5: Minimal surface equation',['../basic_tutorials_minimal_surface_equation.html',1,'']]],
  ['mix_200_3a_20mixed_20formulation_20of_20poisson_20equation_17',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['mix_201_3a_20retrive_20phase_20solving_20transport_20of_20intensity_20equation_18',['MIX-1: Retrive phase solving transport-of-intensity equation.',['../tutorial_phase.html',1,'']]],
  ['mix_202_3a_20mixed_20formulation_20for_20incompressible_20elasticity_19',['MIX-2: Mixed  formulation for incompressible elasticity',['../incompressible_elasticity.html',1,'']]],
  ['mix_20formulation_20unsaturated_20flow_20',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['mixed_20finite_20element_20formulations_20in_20solid_20mechanics_21',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['mixed_20formulation_20and_20integration_20on_20skeleton_20h_20adaptivity_22',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['mixed_20formulation_20for_20incompressible_20elasticity_23',['Mixed formulation for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['mixed_20formulation_20of_20nonlinear_20elasticity_24',['COR-11: Mixed formulation of nonlinear elasticity',['../tutorial_ep.html',1,'tutorials']]],
  ['mixed_20formulation_20of_20poisson_20equation_25',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['model_20and_20navier_20stokes_26',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['model_20creep_20response_20due_20to_20external_20load_27',['Gel Model Creep (response due to external load)',['../gel_creep.html',1,'runningprograms']]],
  ['model_20sorption_20response_20to_20an_20environmental_20change_28',['Gel Model Sorption (response to an environmental change)',['../gel_sorption.html',1,'runningprograms']]],
  ['model_20usage_20example_29',['Gel Model (Usage example)',['../gel_model_example.html',1,'runningprograms']]],
  ['module_30',['Gel Module',['../group__gel.html',1,'']]],
  ['module_31',['module',['../um_bone_remodelling_readnme.html',1,'Bone remodelling module'],['../cell_engineering_readme.html',1,'Cell engineering module'],['../um_eshelbian_plasticity_readme.html',1,'Eshelbian plasticity module'],['../um_fracture_module_readme.html',1,'Fracture mechanics module']]],
  ['module_20and_20program_32',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['module_20v0_2010_200_33',['Mortar Contact Module v0.10.0',['../md_users__modules_2mortar__contact_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['module_20v0_2012_200_34',['Fracture Module v0.12.0',['../md_users__modules_2fracture__mechanics_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['modules_35',['Users modules',['../mod_gallery.html',1,'']]],
  ['mofem_36',['MoFEM',['../contributing_to_mofem.html',1,'Contributing to MoFEM'],['../md_users__modules_2_c_o_n_t_r_i_b_u_t_i_n_g.html',1,'Contributing to MoFEM'],['../publications.html',1,'Selected publications featuring results obtained using MoFEM']]],
  ['mofem_20architecture_37',['MoFEM Architecture',['../general_data_structure.html',1,'']]],
  ['mofem_20authors_38',['MoFEM Authors',['../authors.html',1,'']]],
  ['mofem_20cephas_20strong_39',['&lt;strong&gt;MoFEM (Cephas)&lt;/strong&gt;',['../md__2_users_2likask_2mofem__install_2mofem-cephas_2_r_e_a_d_m_e.html',1,'']]],
  ['mofem_20in_20research_20and_20industry_40',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['mofem_20interfaces_41',['MoFEM Interfaces',['../lessons_introduction.html',1,'']]],
  ['mofem_20ukacm_202021_20school_3a_20weak_20form_20in_20many_20flavours_20design_20and_20sustainable_20code_20development_42',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['mofem_20ukacm_20autumn_20school_202023_3a_20mixed_20finite_20element_20formulations_20in_20solid_20mechanics_43',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['mofem_20v0_2013_200_44',['MoFEM v0.13.0',['../md__c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['mortar_20contact_20module_20v0_2010_200_45',['Mortar Contact Module v0.10.0',['../md_users__modules_2mortar__contact_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['msh_201_3a_20create_20a_202d_20mesh_20from_20gmsh_46',['MSH-1: Create a 2D mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'']]],
  ['msh_202_3a_20create_20a_203d_20mesh_20from_20gmsh_47',['MSH-2: Create a 3D mesh from Gmsh',['../basic_tutorials_mesh_generation_3d.html',1,'']]],
  ['multiplier_48',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]]
];
