var searchData=
[
  ['edf_20tests_0',['Benchmarks crack propagation tests (EDF Tests)',['../benchmarks_edf_tets.html',1,'mod_gallery']]],
  ['eiegn_20problem_1',['Readme for eiegn problem',['../md_tutorials_2vec-1_2_r_e_a_d_m_e.html',1,'']]],
  ['eigen_20elastic_2',['VEC-1: Eigen elastic',['../tutorial_eigen_elastic.html',1,'']]],
  ['elastic_3',['elastic',['../tutorial_eigen_elastic.html',1,'VEC-1: Eigen elastic'],['../tutorial_nonlinear_elastic.html',1,'VEC-2: Nonlinear elastic'],['../tutorial_nonlinear_dynamic_elastic.html',1,'VEC-3: Nonlinear dynamic elastic']]],
  ['elastic_20example_4',['ADV-2: Thermo-elastic example',['../tutorial_thermo_elastic.html',1,'']]],
  ['elasticity_5',['Nonlinear Elasticity',['../elastic_dynamics.html',1,'runningprograms']]],
  ['elasticity_6',['elasticity',['../tutorial_ep.html',1,'COR-11: Mixed formulation of nonlinear elasticity'],['../simple_elasticity_1.html',1,'COR-6: Solid elasticity'],['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity'],['../md_tutorials_2vec-0_2_r_e_a_d_m_e.html',1,'Readme for linear elasticity'],['../tutorial_elastic_problem.html',1,'VEC-0: Linear elasticity']]],
  ['elastoplastic_20plate_7',['Elastoplastic plate',['../jup_tutorial_plastic_problem.html',1,'running_code']]],
  ['element_8',['COR-8: Implementation of spring element',['../spring_element.html',1,'tutorials']]],
  ['element_20formulations_20in_20solid_20mechanics_9',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['element_20mesh_10',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['elsatic_20body_20example_11',['ADV-5: Seepage in elsatic body example',['../tutorial_seepage.html',1,'']]],
  ['engineering_20module_12',['Cell engineering module',['../cell_engineering_readme.html',1,'mod_gallery']]],
  ['environmental_20change_13',['Environmental Change',['../gel_layered.html',1,'Layered Gel Problem (Response to an Environmental Change)'],['../gel_cell.html',1,'Wood Cell (Response to an Environmental Change)']]],
  ['environmental_20change_14',['Gel Model Sorption (response to an environmental change)',['../gel_sorption.html',1,'runningprograms']]],
  ['equation_15',['equation',['../tutorial_navier_stokes.html',1,'COR-10: Navier-Stokes equation'],['../poisson_tut1.html',1,'COR-2: Solving the Poisson equation'],['../poisson_tut2.html',1,'COR-3: Implementing operators for the Poisson equation'],['../poisson_tut4.html',1,'COR-5: A nonlinear Poisson equation'],['../reaction_diffusion_imp.html',1,'COR-9: Reaction-diffusion equation'],['../tut_mix_poisson.html',1,'MIX-0: Mixed formulation of Poisson equation'],['../tutorial_phase.html',1,'MIX-1: Retrive phase solving transport-of-intensity equation.'],['../basic_tutorials_poisson_nonlinear.html',1,'SCL-4: Nonlinear Poisson&apos;s equation'],['../basic_tutorials_minimal_surface_equation.html',1,'SCL-5: Minimal surface equation'],['../basic_tutorials_heat_equation.html',1,'SCL-6: Heat equation'],['../basic_tutorials_wave_equation.html',1,'SCL-7: Wave equation']]],
  ['equation_20homogeneous_20bc_16',['SCL-1: Poisson&apos;s equation (homogeneous BC)',['../basic_tutorials_poisson_homogeneous.html',1,'']]],
  ['equation_20lagrange_20multiplier_17',['SCL-3: Poisson&apos;s equation (Lagrange multiplier)',['../basic_tutorials_poisson_lagrange_multiplier.html',1,'']]],
  ['equation_20non_20homogeneous_20bc_18',['SCL-2: Poisson&apos;s equation (non-homogeneous BC)',['../basic_tutorials_poisson_nonhomogeneous.html',1,'']]],
  ['equation_20on_20sphere_19',['VEC-4: Shallow wave equation on sphere',['../shallow_wave_doc.html',1,'']]],
  ['eshelbian_20plasticity_20module_20',['Eshelbian plasticity module',['../um_eshelbian_plasticity_readme.html',1,'']]],
  ['example_21',['example',['../tutorial_thermo_elastic.html',1,'ADV-2: Thermo-elastic example'],['../tutorial_seepage.html',1,'ADV-5: Seepage in elsatic body example'],['../comp_homo.html',1,'Computational homogenisation (Usage example)'],['../jup_dam_example.html',1,'Dam example'],['../gel_model_example.html',1,'Gel Model (Usage example)'],['../small_strain_plasticity_plate_with_hole.html',1,'Plasticity (User example)']]],
  ['examples_22',['Fracture Mechanics (Usage Examples)',['../frac_mech_simple_examples.html',1,'running_code']]],
  ['exported_20from_20gmsh_20geo_20file_23',['exported from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['external_20load_24',['Gel Model Creep (response due to external load)',['../gel_creep.html',1,'runningprograms']]],
  ['external_20pr_25',['How to: Squashing for an external PR',['../_squash_f_a_q.html',1,'']]]
];
