var searchData=
[
  ['a_202d_20mesh_20from_20gmsh_0',['MSH-1: Create a 2D mesh from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'']]],
  ['a_203d_20mesh_20from_20gmsh_1',['MSH-2: Create a 3D mesh from Gmsh',['../basic_tutorials_mesh_generation_3d.html',1,'']]],
  ['a_20good_20citizen_2',['Being a good citizen',['../being_a_good_citizen.html',1,'']]],
  ['a_20new_20module_20and_20program_3',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['a_20nonlinear_20poisson_20equation_4',['COR-5: A nonlinear Poisson equation',['../poisson_tut4.html',1,'tutorials']]],
  ['a_20program_5',['How to compile a program',['../how_to_compile_program.html',1,'']]],
  ['about_6',['About',['../about_us.html',1,'']]],
  ['acoustics_7',['acoustics',['../md_tutorials_2vec-2_2README.html',1,'Readme for linear acoustics'],['../md_tutorials_2mix-1_2README.html',1,'Readme for linear acoustics'],['../md_tutorials_2clx-0_2README.html',1,'Readme for linear acoustics']]],
  ['adaptivity_8',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['add_20a_20new_20module_20and_20program_9',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['adv_200_3a_20plastic_20problem_10',['ADV-0: Plastic problem',['../tutorial_plastic_problem.html',1,'']]],
  ['adv_201_3a_20contact_20problem_11',['ADV-1: Contact problem',['../tutorial_contact_problem.html',1,'']]],
  ['adv_202_3a_20thermo_20elastic_20example_12',['ADV-2: Thermo-elastic example',['../tutorial_thermo_elastic.html',1,'']]],
  ['adv_203_3a_20dg_20upwind_20for_20advection_20problem_20or_20level_20set_13',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['adv_205_3a_20seepage_20in_20elsatic_20body_20example_14',['ADV-5: Seepage in elsatic body example',['../tutorial_seepage.html',1,'']]],
  ['advanced_15',['advanced',['../install_docker_advanced.html',1,'Installation with Docker - advanced'],['../installation_with_spack.html',1,'Installation with Spack (Advanced)']]],
  ['advection_20problem_20or_20level_20set_16',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['an_20external_20pr_17',['How to: Squashing for an external PR',['../SquashFAQ.html',1,'']]],
  ['and_20dm_20sub_20problem_18',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['and_20industry_19',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['and_20integration_20on_20skeleton_20h_20adaptivity_20',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['and_20login_21',['Password and login',['../md__2home_2lk58p_2mofem__install_2vanilla__dev__release_2mofem-cephas_2jupyter_2templates_2login__notes.html',1,'']]],
  ['and_20navier_20stokes_22',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['and_20program_23',['How to add a new module and program',['../how_to_add_new_module_and_program.html',1,'']]],
  ['and_20sustainable_20code_20development_24',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['applications_20of_20mofem_20in_20research_20and_20industry_25',['Applications of MoFEM in research and industry',['../applications.html',1,'']]],
  ['approximation_26',['FUN-2: Hierarchical approximation',['../hierarchical_approximation_1.html',1,'']]],
  ['approximaton_27',['SCL-0: Least square approximaton',['../basic_tutorials_least_square_approximation.html',1,'']]],
  ['architecture_28',['MoFEM Architecture',['../general_data_structure.html',1,'']]],
  ['asked_20questions_29',['Frequently Asked Questions',['../faqs.html',1,'']]],
  ['authors_30',['MoFEM Authors',['../authors.html',1,'']]],
  ['autumn_20school_202023_3a_20mixed_20finite_20element_20formulations_20in_20solid_20mechanics_31',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]]
];
