var searchData=
[
  ['features_0',['Features',['../motivation.html',1,'']]],
  ['featuring_20results_20obtained_20using_20mofem_1',['Selected publications featuring results obtained using MoFEM',['../publications.html',1,'']]],
  ['field_20model_20and_20navier_20stokes_2',['VEC-5: Phase field model and Navier-Stokes',['../phase_field_doc.html',1,'']]],
  ['fieldsplit_20solver_20and_20dm_20sub_20problem_3',['COR-4: Using fieldsplit solver and DM sub problem.',['../poisson_tut3.html',1,'tutorials']]],
  ['file_4',['file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['file_20exported_20from_20gmsh_20geo_20file_5',['file exported from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['file_20from_20med_20file_20exported_20from_20gmsh_20geo_20file_6',['file from med file exported from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['film_20spanned_20on_20wire_7',['Soap film spanned on wire',['../sope_film.html',1,'tutorials']]],
  ['finite_20element_20formulations_20in_20solid_20mechanics_8',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['finite_20element_20mesh_9',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['flavours_20design_20and_20sustainable_20code_20development_10',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['flow_11',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['for_20advection_20problem_20or_20level_20set_12',['ADV-3: DG Upwind for advection problem or level set',['../tutorial_level_set.html',1,'']]],
  ['for_20an_20external_20pr_13',['How to: Squashing for an external PR',['../_squash_f_a_q.html',1,'']]],
  ['for_20bug_20reporting_14',['Guidelines for bug reporting',['../guidelines_bug_reporting.html',1,'']]],
  ['for_20computational_20homogenisation_15',['Convergence studies for computational homogenisation',['../convergence_studies.html',1,'runningprograms']]],
  ['for_20eiegn_20problem_16',['Readme for eiegn problem',['../md_tutorials_2vec-1_2_r_e_a_d_m_e.html',1,'']]],
  ['for_20incompressible_20elasticity_17',['for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['for_20kirchoff_20love_20plate_18',['VEC-6: Discontinuous Galerkin for Kirchoff-Love Plate',['../tutorial_plate.html',1,'']]],
  ['for_20linear_20acoustics_19',['for linear acoustics',['../md_tutorials_2clx-0_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics'],['../md_tutorials_2mix-1_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics'],['../md_tutorials_2vec-2_2_r_e_a_d_m_e.html',1,'Readme for linear acoustics']]],
  ['for_20linear_20elasticity_20',['Readme for linear elasticity',['../md_tutorials_2vec-0_2_r_e_a_d_m_e.html',1,'']]],
  ['for_20plasticity_21',['VEC-7: Automatic Differentiation for Plasticity',['../tutorial_adolc_plasticity.html',1,'']]],
  ['for_20poisson_20problem_22',['SCL-11: Discontinuous Galerkin for Poisson problem',['../tutorial_dg_poisson.html',1,'']]],
  ['for_20the_20poisson_20equation_23',['COR-3: Implementing operators for the Poisson equation',['../poisson_tut2.html',1,'tutorials']]],
  ['force_24',['MAX-1: Lorenz force',['../tutorial_lorenz_force.html',1,'']]],
  ['fork_25',['Tuning fork',['../jup_tutorial_eigen_elastic.html',1,'running_code']]],
  ['form_20in_20many_20flavours_20design_20and_20sustainable_20code_20development_26',['MoFEM UKACM 2021 School: &quot;Weak form&quot; in many flavours. Design and sustainable code development',['../mofem_school_2021.html',1,'']]],
  ['formulation_20and_20integration_20on_20skeleton_20h_20adaptivity_27',['COR-0: Mixed formulation and integration on skeleton (h-adaptivity)',['../mix_transport.html',1,'tutorials']]],
  ['formulation_20for_20incompressible_20elasticity_28',['formulation for incompressible elasticity',['../elasticity_mixed_formulation.html',1,'COR-7: Mixed formulation for incompressible elasticity'],['../incompressible_elasticity.html',1,'MIX-2: Mixed  formulation for incompressible elasticity']]],
  ['formulation_20of_20nonlinear_20elasticity_29',['COR-11: Mixed formulation of nonlinear elasticity',['../tutorial_ep.html',1,'tutorials']]],
  ['formulation_20of_20poisson_20equation_30',['MIX-0: Mixed formulation of Poisson equation',['../tut_mix_poisson.html',1,'']]],
  ['formulation_20unsaturated_20flow_31',['COR-1: Time dependent nonlinear mix formulation (unsaturated flow)',['../mix_us_flow.html',1,'tutorials']]],
  ['formulations_20in_20solid_20mechanics_32',['MoFEM UKACM Autumn School 2023: Mixed Finite Element Formulations in Solid Mechanics',['../mofem_school_2023.html',1,'']]],
  ['fracture_20mechanics_20module_33',['Fracture mechanics module',['../um_fracture_module_readme.html',1,'mod_gallery']]],
  ['fracture_20mechanics_20usage_20examples_34',['Fracture Mechanics (Usage Examples)',['../frac_mech_simple_examples.html',1,'running_code']]],
  ['fracture_20module_20v0_2012_200_35',['Fracture Module v0.12.0',['../md_users__modules_2fracture__mechanics_2_c_h_a_n_g_e_l_o_g.html',1,'']]],
  ['frequently_20asked_20questions_36',['Frequently Asked Questions',['../faqs.html',1,'']]],
  ['from_20core_37',['How to Copy a Tutorial from Core',['../md_users__modules_2_how_to_copy_tutorial.html',1,'']]],
  ['from_20ct_20scans_38',['Density mapping from CT scans',['../density_map_example.html',1,'runningprograms']]],
  ['from_20gmsh_39',['from Gmsh',['../basic_tutorials_mesh_generation_2d.html',1,'MSH-1: Create a 2D mesh from Gmsh'],['../basic_tutorials_mesh_generation_3d.html',1,'MSH-2: Create a 3D mesh from Gmsh']]],
  ['from_20gmsh_20geo_20file_40',['from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['from_20med_20file_20exported_20from_20gmsh_20geo_20file_41',['from med file exported from Gmsh geo file',['../md_tutorials_2msh-1_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)'],['../md_tutorials_2msh-2_2_r_e_a_d_m_e.html',1,'Use read_med to create *.h5m file from *.med file (exported from Gmsh *.geo file)']]],
  ['ftensor_20library_42',['FTensor library',['../group__ftensor.html',1,'']]],
  ['fun_200_3a_20hello_20world_43',['FUN-0: Hello world',['../hello_world_tut1.html',1,'']]],
  ['fun_201_3a_20integration_20on_20finite_20element_20mesh_44',['FUN-1: Integration on finite element mesh',['../integration.html',1,'']]],
  ['fun_202_3a_20hierarchical_20approximation_45',['FUN-2: Hierarchical approximation',['../hierarchical_approximation_1.html',1,'']]],
  ['functions_46',['Genarting base functions',['../md_tutorials_2fun-2_2_r_e_a_d_m_e.html',1,'']]]
];
